In [1]:
# Setup
import torch
import copy
import json

from utils.data_reader import load_and_prepare_time_series_data
from utils.evaluator import Evaluator
from models.baseline_models import LSTMModel, BiLSTMModel, GRUModel
from models.custom_models import MGSSMModel, MGSSMsModel, ExtendedMGSSMsModel

In [2]:

selected_country_codes = ['US', 'IN', 'BR', 'FR', 'DE',
                         'GB', 'RU', 'IT', 'TR', 'ES',
                         'VN', 'AR', 'AU', 'AT', 'BD',
                         'BE', 'BG', 'CA', 'CL', 'CN',
                         'CU', 'DK', 'FI', 'GE', 'GR',
                         'ID', 'JP', 'JO', 'KE', 'KR',
                         'LR', 'MY','ML', 'MX', 'NL',
                         'NO', 'PH','SE', 'CH', 'TH']

# Fetch and prepare the data for each country code
with open("/home/theppawan/nn-models/data/COVID19_url_data.json", "r") as f:
    dataset = json.load(f)

train_loader_dist = {}
val_loader_dist = {}
test_loader_dist = {}
scaler_dist = {}
for key in selected_country_codes:
    train_loader, val_loader, test_loader, scaler = load_and_prepare_time_series_data(
        filepath_or_url = dataset['region'].format(region=key),
        target_column=['cumulative_confirmed'],
        date_column="date",
        seq_length=14,
        batch_size=64,
        train_split=0.8,
        fill_missing=True)
    train_loader_dist[key] = train_loader
    val_loader_dist[key] = val_loader
    test_loader_dist[key] = test_loader
    scaler_dist[key] = scaler

# Setup model configurations
model_config_dict = {
    "Baseline LSTM": LSTMModel(input_size=1, hidden_size=256, num_layers=1, output_size=1),
    "Baseline BiLSTM": BiLSTMModel(input_size=1, hidden_size=256, num_layers=1, output_size=1),
    "Baseline GRU": GRUModel(input_size=1, hidden_size=128, num_layers=1, output_size=1),
    "MGSSM": MGSSMModel(input_size=1, hidden_size=64, num_layers=1, output_size=1, gate_size=32),
    "MGSSMs": MGSSMsModel(input_size=1, hidden_size=64, num_layers=1, output_size=1, gate_size=32),
    "ExtendedMGSSMs": ExtendedMGSSMsModel(input_size=1, hidden_size=64, num_layers=1, output_size=1, gate_size=32, p=2)
}

Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/US.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/IN.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/BR.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/FR.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/DE.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/GB.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/RU.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/IT.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/TR.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/ES.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/VN.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/AR.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/AU.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/AT.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/BD.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/BE.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/BG.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/CA.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/CL.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/CN.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/CU.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/DK.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/FI.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/GE.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/GR.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/ID.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/JP.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/JO.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/KE.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/KR.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/LR.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/MY.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/ML.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/MX.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/NL.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/NO.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/PH.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/SE.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/CH.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3
Fetching data from: https://storage.googleapis.com/covid19-open-data/v3/location/TH.csv
Sorting data chronologicall by column: date
Succesfully loaded 991 sequential data points.
Prepared Training batches: 13 | Validation batches: 3

In [3]:
trained_model_dict = {key: {} for key in selected_country_codes}
# loading the checkpointed models
for model_name, model_config in model_config_dict.items():
    # analyze the model from the checkpoint
    for key in selected_country_codes:
        country_specific_model = copy.deepcopy(model_config)
        country_specific_model.load_state_dict(torch.load(f"checkpoints/best_{model_config.__class__.__name__}_{key}.pth"))
        trained_model_dict[key][model_name] = country_specific_model

evaluator = Evaluator()
for key in selected_country_codes:
    val_loader = val_loader_dist[key]
    scaler = scaler_dist[key]
    evaluator.compare_models(trained_model_dict[key], val_loader, scaler)

Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...
Evaluating model: Baseline LSTM...
Evaluating model: Baseline BiLSTM...
Evaluating model: Baseline GRU...
Evaluating model: MGSSM...
Evaluating model: MGSSMs...
Evaluating model: ExtendedMGSSMs...

In [4]:
performance_data = evaluator.build_performance_dataframe(nested_models_dict=trained_model_dict, data_loaders_dict=val_loader_dist, scalers_dict=scaler_dist, target_metric="MSE")
performance_data

Evaluating models for dataset: US...
Evaluating models for dataset: IN...
Evaluating models for dataset: BR...
Evaluating models for dataset: FR...
Evaluating models for dataset: DE...
Evaluating models for dataset: GB...
Evaluating models for dataset: RU...
Evaluating models for dataset: IT...
Evaluating models for dataset: TR...
Evaluating models for dataset: ES...
Evaluating models for dataset: VN...
Evaluating models for dataset: AR...
Evaluating models for dataset: AU...
Evaluating models for dataset: AT...
Evaluating models for dataset: BD...
Evaluating models for dataset: BE...
Evaluating models for dataset: BG...
Evaluating models for dataset: CA...
Evaluating models for dataset: CL...
Evaluating models for dataset: CN...
Evaluating models for dataset: CU...
Evaluating models for dataset: DK...
Evaluating models for dataset: FI...
Evaluating models for dataset: GE...
Evaluating models for dataset: GR...
Evaluating models for dataset: ID...
Evaluating models for dataset: JP...
Evaluating models for dataset: JO...
Evaluating models for dataset: KE...
Evaluating models for dataset: KR...
Evaluating models for dataset: LR...
Evaluating models for dataset: MY...
Evaluating models for dataset: ML...
Evaluating models for dataset: MX...
Evaluating models for dataset: NL...
Evaluating models for dataset: NO...
Evaluating models for dataset: PH...
Evaluating models for dataset: SE...
Evaluating models for dataset: CH...
Evaluating models for dataset: TH...

,Baseline LSTM,Baseline BiLSTM,Baseline GRU,MGSSM,MGSSMs,ExtendedMGSSMs
US,3.275813e+10,2.931701e+10,4.189532e+09,1.532140e+11,3.118342e+10,3.956473e+10
IN,1.001611e+08,1.809958e+07,5.436851e+07,7.340424e+08,1.349523e+08,5.507878e+07
BR,6.419532e+08,3.175263e+08,1.102976e+09,6.619543e+09,1.096989e+10,1.960648e+09
FR,8.544586e+12,5.074134e+12,9.218955e+12,5.379041e+12,4.287771e+12,4.080967e+12
DE,7.664578e+09,2.921927e+09,5.748462e+09,7.553129e+09,2.471913e+10,3.706762e+09
GB,1.986474e+09,1.151065e+08,2.411332e+09,2.285068e+09,3.566276e+08,1.597134e+08
RU,3.332873e+08,1.195091e+08,1.044799e+09,3.249092e+08,4.815562e+08,1.544701e+08
IT,8.869321e+09,2.880845e+08,3.368396e+10,1.150071e+09,4.206722e+09,2.049500e+09
TR,3.791880e+09,4.576516e+09,5.167199e+09,3.664900e+09,3.254723e+09,2.992440e+09
ES,2.155764e+08,1.734645e+08,5.772648e+08,5.059242e+08,4.794276e+09,2.749089e+08
VN,1.888572e+10,2.570119e+09,4.600795e+09,3.660926e+09,2.890215e+09,2.383004e+09
AR,1.351736e+08,7.711696e+07,1.188659e+08,1.347622e+08,3.217416e+08,9.544526e+07
AU,2.370396e+08,5.521037e+08,1.027820e+09,1.540906e+08,5.422540e+08,2.071085e+08
AT,9.692869e+07,1.517182e+07,5.308206e+08,3.946274e+07,4.349882e+08,4.751610e+07
BD,1.048381e+05,2.082131e+05,1.439453e+05,1.069900e+05,2.590170e+05,2.061600e+05
BE,1.928686e+07,9.698342e+06,1.243812e+07,1.843545e+07,3.643177e+07,9.942529e+06
BG,2.300775e+05,2.373552e+05,3.007218e+05,4.396953e+05,4.527474e+05,3.738423e+05
CA,9.846308e+10,8.097167e+10,1.461121e+11,1.250874e+11,1.248318e+11,1.118407e+11
CL,7.182240e+06,2.244151e+07,1.457565e+07,1.474134e+07,4.982016e+07,6.537950e+07
CN,2.370696e+10,1.707880e+10,4.367446e+10,2.694683e+10,2.416310e+10,2.082798e+10
CU,7.152947e+04,5.823687e+03,1.635435e+04,1.931386e+04,1.157069e+05,5.882561e+04
DK,5.113978e+06,2.386152e+06,1.745927e+06,4.471716e+06,8.904945e+06,9.800661e+06
FI,3.988426e+07,3.581175e+07,3.487599e+07,4.194611e+07,1.473344e+08,5.340378e+07
GE,7.503684e+06,6.509128e+06,6.523305e+06,9.716533e+06,7.577256e+06,7.376923e+06
GR,6.692911e+08,5.544143e+08,5.631433e+08,6.928872e+08,6.391492e+08,5.716088e+08
ID,1.338153e+06,9.786168e+05,1.518412e+06,1.370843e+06,1.088654e+08,6.120978e+06
JP,1.472139e+09,2.509084e+09,1.642210e+09,1.952604e+09,8.671599e+10,7.369904e+09
JO,1.747725e+06,1.622010e+06,1.673576e+06,3.963418e+06,9.555041e+06,2.195624e+06
KE,3.439907e+03,2.295636e+03,3.232980e+03,1.012635e+04,9.357344e+04,2.137562e+04
KR,6.976826e+09,1.618381e+11,1.767734e+10,7.493239e+10,5.688352e+10,8.878781e+09
LR,3.828792e+01,3.964737e+01,3.819542e+01,4.570638e+01,6.114856e+01,4.416272e+01
MY,1.450580e+06,4.230373e+06,3.164514e+06,3.857760e+06,3.831477e+08,1.547671e+07
ML,1.789278e+02,1.567793e+02,1.584274e+02,2.554099e+02,5.059230e+02,5.133933e+02
MX,7.588002e+07,9.274960e+07,1.109682e+08,7.315583e+07,1.161568e+08,8.938376e+07
NL,4.662256e+07,5.306248e+08,3.703375e+07,6.169395e+08,9.119129e+08,4.535619e+07
NO,6.757195e+05,3.148420e+05,7.574195e+05,4.550726e+06,1.531430e+07,1.355578e+06
PH,2.712649e+06,2.274261e+06,2.110329e+06,4.781036e+06,5.979180e+06,3.900364e+06
SE,1.180253e+05,1.073811e+05,1.177514e+05,1.737605e+06,9.988933e+05,3.129542e+05
CH,6.644528e+06,6.470806e+06,6.331204e+06,2.852775e+07,2.288684e+08,1.298975e+07
TH,1.492486e+06,7.111818e+06,1.633641e+06,1.147416e+07,5.317248e+06,5.207237e+06

In [5]:
friedman_statistic, p_value = evaluator.friedman_test(performance_data)
p_value

np.float64(2.38304347856472e-10)

In [6]:
evaluator.holm_bonferroni_posthoc(performance_data, control_model="ExtendedMGSSMs", alpha=0.05, metric_is_loss=True)

,unadjusted p-value,Step (i),Holm threshold,Holm adjusted p-value,reject null hypothesis
baseline model,,,,,
MGSSMs,8.171992e-08,1,0.010000,4.085996e-07,True
MGSSM,4.890999e-03,2,0.012500,1.956400e-02,True
Baseline GRU,1.876903e-01,3,0.016667,5.630708e-01,False
Baseline LSTM,4.183775e-01,4,0.025000,8.367550e-01,False
Baseline BiLSTM,9.934871e-01,5,0.050000,9.934871e-01,False